### ISSUE TITLE
The state is lost when switching from desktop to mobile view and vice-versa

### ISSUE THREAD

**Issue by TiagooGomess** [NIAEFEUP/nijobs-fe#115]
The session was being lost in some pages, so we needed to set revalidateOnMount to true [here](https://github.com/NIAEFEUP/nijobs-fe/blob/develop/src/components/Navbar/index.js#L30), in #105.

Because of this change, the state is being lost in some pages when switching from desktop to mobile view or vice-versa, namely in the finish registration page.

What is happening is:
1. Unmount of PageLayout
2. Show loading
3. Mount PageLayout again

A possible solution for this is to do not let PageLayout re-render, even if the session changes. In theory, we can try to move the Controller Pattern to the Route level, but we need to see if that would work.

**Comment by imnotteixeira** [comment]
Just to clarify, since we added `revalidateOnMount: true` on the navbar useSession call, every time the navbar is mounted, the session is revalidated. Such thing happens when we change from desktop to mobile layout, since the layout changes, so the navbar is remounted, and the session will then be revalidated, causing the route to enter the isValidating state (unmounting the PageLayout, rendering the Loading Bar and re mounting the PageLayout after the session is revalidated, which makes the state in PageLayout be lost).

I am 99% sure the change of moving the controller pattern to the route level will do the trick (having the useComponentController call in the Route instead of PageLayout, by maybe creating a StatefulRoute abstraction, which receives the controller, context etc), but we need to verify this.
