### ISSUE TITLE
Unable to remove optional offer fields 

### ISSUE THREAD

**Issue by BrunoRosendo** [NIAEFEUP/nijobs-fe#250]
Whenever an offer has an optional field (e.g. vacancies) it's not possible to remove them by editing the offer
They is probably being wrongly filtered out because the respective from fields are empty

**Comment by AvilaAndre** [comment]
They are being filtered out because when they are removed (or when the vacancies value is set to 0) their value becomes undefined, which is not a valid JSON value, therefore the back-end never receives anything, however, the back-end asks for a number equal or greater than 0 (for vacancies) and a Date (for the jobStartDate), the reason vacancies do not appear when the user doesn't input them on creation is because they are never sent to the back-end and therefore vacancies do not exist there, once they do it it can't be reset.

**Comment by AvilaAndre** [comment]
For the vacancies I even though of having a default value of 0 but for the others it's a bit more complicated than that.

**Comment by BrunoRosendo** [comment]
@AvilaAndre Is it easy to, instead of undefined, send a `null` to the BE? That should solve things

**Comment by AvilaAndre** [comment]
Sending a null brings up an error unfortunately.
![image](https://user-images.githubusercontent.com/75994325/194819660-447a7bd4-1eb2-4f36-a7c8-1952fc054d7f.png)

**Comment by BrunoRosendo** [comment]
@AvilaAndre You're right... That means the backend also has problems with this. Can you please open an issue on https://github.com/NIAEFEUP/nijobs-be/issues ?

**Comment by BrunoRosendo** [comment]
Explain that adding `{ nullable: true }` to the `optional()` validator seems to solve things. After that's fixed, the frontend will be able to send `null` and get the expected behaviour

**Comment by BrunoRosendo** [comment]
I created https://github.com/NIAEFEUP/nijobs-be/issues/260

**Comment by BrunoRosendo** [comment]
@AvilaAndre The BE fix is ready for review
