### ISSUE TITLE
Add Page Layout

### ISSUE THREAD

**Issue by monkin77** [NIAEFEUP/nijobs-fe#71]
Create a page layout that will render all pages with the footer.

**Comment by imnotteixeira** [comment]
An important aspect of this is to make sure that it doesn't break the current layout (I.e. the centered stuff is still centered vertically etc)

Additionally, I think the Navbar should be a part of the layout as currently there is no way of navigating between pages. The layout should have a prop that allows disabling the Homepage button so that it doesn't show on the homepage's navbar, only on other pages)
